version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["security", "dependencies"]
    commit-message:
      prefix: "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Europe/London"
    labels: ["dependencies"]
