# Dependabot — ISO 27001 A.12.6 Vulnerability Management
# PIOS v2.4.2 | VeritasIQ Technologies Ltd
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["security", "dependencies"]
    commit-message:
      prefix: "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["security", "github-actions"]
