/**
 * POST /api/notifications/smart
 * Smart notification engine — AI-prioritised, context-aware alerts.
 *
 * Actions:
 *   generate   — scan PIOS state, generate prioritised notification digest
 *   push-agent — push notifications generated by a background agent run
 *   digest     — generate morning digest briefing
 *
 * PIOS™ v3.4.1 | Sprint J — Smart Notifications | VeritasIQ Technologies Ltd
 */
import { NextRequest, NextResponse } from 'next/server'
import { createClient }              from '@/lib/supabase/server'
import Anthropic                     from '@anthropic-ai/sdk'

export const dynamic    = 'force-dynamic'
export const maxDuration = 60
const anthropic = new Anthropic()

const NOTIFICATION_TYPES = {
  urgent:     { icon: '🔴', priority: 1, label: 'Urgent'     },
  warning:    { icon: '🟡', priority: 2, label: 'Warning'    },
  info:       { icon: '🔵', priority: 3, label: 'Info'       },
  success:    { icon: '🟢', priority: 4, label: 'Success'    },
  academic:   { icon: '🎓', priority: 2, label: 'Academic'   },
  ip:         { icon: '⚖',  priority: 2, label: 'IP & Legal' },
  platform:   { icon: '🔧', priority: 2, label: 'Platform'   },
  agent:      { icon: '🤖', priority: 3, label: 'Agent'      },
}

export async function POST(req: NextRequest) {
  try {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const body   = await req.json()
    const action = body.action ?? 'generate'

    // ── Generate — scan PIOS state + AI prioritisation ───────────────────
    if (action === 'generate') {
      const today = new Date().toISOString().slice(0, 10)
      const in7   = new Date(Date.now() + 7 * 86400_000).toISOString().slice(0, 10)

      // Parallel state fetch
      const [tasks, ipAssets, chapters, insights, agentRuns] = await Promise.all([
        supabase.from('tasks').select('id,title,priority,status,due_date').eq('user_id', user.id)
          .in('status', ['todo','in_progress']).order('due_date', { ascending: true }).limit(30),
        supabase.from('ip_assets').select('id,name,asset_type,renewal_date,status').eq('user_id', user.id)
          .eq('status', 'active').lte('renewal_date', in7).gte('renewal_date', today),
        supabase.from('thesis_chapters').select('id,chapter_num,title,status,word_count,target_words').eq('user_id', user.id),
        supabase.from('insights').select('id,content,category,created_at').eq('user_id', user.id)
          .gte('created_at', new Date(Date.now() - 24 * 3600_000).toISOString()).limit(5),
        supabase.from('user_agents').select('agent_id,last_run_at,last_run_status,last_run_output')
          .eq('user_id', user.id).eq('last_run_status', 'success')
          .gte('last_run_at', new Date(Date.now() - 24 * 3600_000).toISOString()).limit(3),
      ])

      const overdueTasks = (tasks.data ?? []).filter((t: any) => t.due_date && t.due_date < today)
      const dueSoonTasks = (tasks.data ?? []).filter((t: any) => t.due_date && t.due_date >= today && t.due_date <= in7)
      const renewals     = ipAssets.data ?? []

      // Build notifications array
      const notifications: Array<{
        title: string; body: string; type: string; priority: number; action_url?: string
      }> = []

      // Overdue tasks
      if (overdueTasks.length > 0) {
        notifications.push({
          title: `${overdueTasks.length} overdue task${overdueTasks.length > 1 ? 's' : ''}`,
          body:  overdueTasks.slice(0, 3).map((t: any) => t.title).join(' · '),
          type:  'urgent', priority: 1, action_url: '/platform/tasks',
        })
      }

      // Due-soon tasks
      if (dueSoonTasks.length > 0) {
        notifications.push({
          title: `${dueSoonTasks.length} task${dueSoonTasks.length > 1 ? 's' : ''} due this week`,
          body:  dueSoonTasks.slice(0, 3).map((t: any) => t.title).join(' · '),
          type:  'warning', priority: 2, action_url: '/platform/tasks',
        })
      }

      // IP renewal alerts
      for (const asset of renewals) {
        const daysLeft = Math.round((new Date(String(asset.renewal_date)).getTime() - Date.now()) / 86400_000)
        notifications.push({
          title: `IP renewal due in ${daysLeft} day${daysLeft !== 1 ? 's' : ''}`,
          body:  `${asset.name} (${asset.asset_type}) — renewal_date: ${asset.renewal_date}`,
          type:  daysLeft <= 3 ? 'urgent' : 'ip', priority: daysLeft <= 3 ? 1 : 2,
          action_url: '/platform/ip-vault',
        })
      }

      // DBA chapter progress
      const chapData = chapters.data ?? []
      const totalWords  = chapData.reduce((s: number, c: any) => s + (c.word_count ?? 0), 0)
      const targetWords = chapData.reduce((s: number, c: any) => s + (c.target_words ?? 8000), 0)
      const progressPct = targetWords > 0 ? Math.round(totalWords / targetWords * 100) : 0
      if (progressPct < 30 && chapData.length > 0) {
        notifications.push({
          title: `DBA thesis at ${progressPct}% — Qiddiya RFP deadline 14 Apr`,
          body:  `${totalWords.toLocaleString()} / ${targetWords.toLocaleString()} words across ${chapData.length} chapters`,
          type:  'academic', priority: 2, action_url: '/platform/academic',
        })
      }

      // New insights (if any)
      if ((insights.data ?? []).length > 0) {
        notifications.push({
          title: `${insights.data!.length} new insight${insights.data!.length > 1 ? 's' : ''} captured`,
          body:  insights.data!.slice(0, 2).map((i: any) => String(i.content).slice(0, 50)).join(' · '),
          type:  'info', priority: 3, action_url: '/platform/intelligence',
        })
      }

      // Agent run summaries
      for (const agent of (agentRuns.data ?? [])) {
        const output = String(agent.last_run_output ?? '').slice(0, 100)
        notifications.push({
          title: `Agent: ${agent.agent_id?.replace(/_/g, ' ')} completed`,
          body:  output,
          type:  'agent', priority: 3, action_url: '/platform/agents',
        })
      }

      // Sort by priority
      notifications.sort((a, b) => a.priority - b.priority)

      // AI prioritisation — pick top 5 and write smart copy
      const stateText = notifications.slice(0, 10)
        .map(n => `[${n.type.toUpperCase()}] ${n.title}: ${n.body}`)
        .join('\n')

      const msg = await anthropic.messages.create({
        model: 'claude-haiku-4-5-20251001', max_tokens: 400,
        messages: [{ role: 'user', content:
          `PIOS smart notification engine. Rewrite these notifications as concise, actionable PIOS alerts.\n\n` +
          `Raw signals:\n${stateText}\n\n` +
          `Return exactly the top 5 most important as JSON array (no markdown):\n` +
          `[{"title":<15 words max>,"body":<20 words max>,"type":<keep original type>,"action_url":<keep>}]`
        }],
      })

      let smartNotifs = notifications.slice(0, 5)
      try {
        const raw = msg.content[0]?.type === 'text' ? msg.content[0].text : '[]'
        const parsed = JSON.parse(raw.replace(/```json|```/g,'').trim())
        if (Array.isArray(parsed) && parsed.length) smartNotifs = parsed.map((n: any, i: number) => ({
          ...n, priority: notifications[i]?.priority ?? 3,
        }))
      } catch { /* use unstyled */ }

      // Insert into notifications table
      const toInsert = smartNotifs.map(n => ({
        user_id:    user.id,
        title:      n.title,
        body:       n.body,
        type:       n.type ?? 'info',
        action_url: (n as any).action_url ?? null,
        read:       false,
        source:     'smart_engine',
        created_at: new Date().toISOString(),
      }))

      await supabase.from('notifications').insert(toInsert)

      return NextResponse.json({
        ok: true, action: 'generate',
        generated: smartNotifs.length,
        notifications: smartNotifs,
        state_summary: { overdue: overdueTasks.length, due_soon: dueSoonTasks.length, ip_renewals: renewals.length, dba_progress_pct: progressPct },
      })
    }

    // ── Digest — morning executive digest ─────────────────────────────────
    if (action === 'digest') {
      const { notifications: notifs } = body
      const items = (notifs as any[] ?? []).slice(0, 10)
        .map((n: any) => `[${n.type?.toUpperCase()}] ${n.title}: ${n.body}`)
        .join('\n')

      const msg = await anthropic.messages.create({
        model: 'claude-haiku-4-5-20251001', max_tokens: 350,
        messages: [{ role: 'user', content:
          `PIOS Chief of Staff. Write a morning digest (max 5 bullets, each ≤12 words).\n\nAlerts:\n${items || 'No alerts.'}\n\nBe direct. Start with most urgent. Format: bullet list, no headers.`
        }],
      })
      const digest = msg.content[0]?.type === 'text' ? msg.content[0].text : ''
      return NextResponse.json({ ok: true, action: 'digest', digest })
    }

    return NextResponse.json({ error: `Unknown action: ${action}` }, { status: 400 })
  } catch (err: any) {
    console.error('[PIOS notifications/smart]', err)
    return NextResponse.json({ error: err?.message ?? 'Internal server error' }, { status: 500 })
  }
}
