import { NextRequest, NextResponse } from 'next/server'
import { apiError } from '@/lib/api-error'
import { requireOwnedEngagement } from '@/app/api/fm/_shared'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

type RouteParams = { id: string }

type ReportFormat = 'markdown' | 'html' | 'pdf'

function toMarkdown(input: {
  engagement: Record<string, any>
  frameworks: Record<string, any>[]
  steps: Record<string, any>[]
  risks: Record<string, any>[]
  options: Record<string, any>[]
}) {
  const { engagement, steps, frameworks, risks, options } = input
  const topRisks = [...risks].sort((a, b) => Number(b.risk_score ?? 0) - Number(a.risk_score ?? 0)).slice(0, 5)
  const recommended = options.find((opt) => opt.is_recommended) ?? options[0]

  const stepBlocks = steps
    .map((step) => {
      const runs = frameworks.filter((f) => Number(f.step_number) === Number(step.step_number))
      const snippets = runs
        .slice(0, 2)
        .map((run) => `- **${run.framework_code}**: ${String(run.output?.analysis ?? JSON.stringify(run.output ?? {})).slice(0, 280)}`)
        .join('\n')
      return `### Step ${step.step_number}\n- Gate: ${step.gate_status}\n- Confidence: ${Math.round(Number(step.confidence_score ?? 0) * 100)}%\n${snippets || '- No framework outputs yet.'}`
    })
    .join('\n\n')

  const riskTable = topRisks.length
    ? topRisks
        .map(
          (risk, idx) =>
            `${idx + 1}. **${risk.risk_library?.risk_code ?? risk.custom_title ?? 'Custom risk'}** — ${risk.risk_library?.title ?? risk.custom_title ?? 'Untitled risk'} (P:${risk.probability}, I:${risk.impact}, Score:${risk.risk_score})`
        )
        .join('\n')
    : '- No risks logged.'

  const optionTable = options.length
    ? options
        .map(
          (opt) =>
            `| ${opt.option_number} | ${opt.title} | ${opt.risk_level ?? 'n/a'} | £${Number(opt.estimated_cost_min ?? 0).toLocaleString()} - £${Number(opt.estimated_cost_max ?? 0).toLocaleString()} | ${opt.implementation_time_weeks ?? 'n/a'} | ${opt.is_recommended ? '✅' : ''} |`
        )
        .join('\n')
    : '| n/a | n/a | n/a | n/a | n/a | n/a |'

  const recommendationText = recommended
    ? `**Recommended option:** ${recommended.title}\n\n${recommended.recommendation_reasoning ?? 'Selected as the best balance of impact, risk, and implementation realism.'}`
    : 'No recommendation selected yet.'

  return `# FM Engagement Report\n\n## Executive Summary\nEngagement **${engagement.title}** for **${engagement.client_name}** is currently in phase **${engagement.current_phase ?? 'setup'}** and step **${engagement.current_step ?? 1}**. This report summarises engagement objectives, workbench outputs, key risks, strategic options, and final recommendation.\n\n## Engagement Overview\n- Engagement type: ${engagement.fm_engagement_type_code ?? engagement.engagement_type}\n- Industry sector: ${engagement.industry_sector ?? 'n/a'}\n- Building type: ${engagement.building_type ?? 'n/a'}\n- Project scale: ${engagement.project_scale ?? 'n/a'}\n- Status: ${engagement.status}\n- Dates: ${engagement.start_date ?? 'n/a'} → ${engagement.end_date ?? 'n/a'}\n\n## Objectives\n${engagement.brief ?? 'No explicit objective statement captured.'}\n\n## Step-by-step Outputs\n${stepBlocks}\n\n## Risk Register Summary (Top 5)\n${riskTable}\n\n## Options Comparison\n| Option | Title | Risk | Cost Range (GBP) | Time (weeks) | Recommended |\n|---|---|---|---|---|---|\n${optionTable}\n\n## Recommendations\n${recommendationText}\n\n## Appendices\n- Full framework outputs are available in engagement framework runs\n- Full risk register and mitigation plans available in Risk Register tab\n- Full options details and assumptions available in Options tab\n`
}

function markdownToHtml(markdown: string, accent = '#6349ff') {
  const escaped = markdown
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br/>')
  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>FM Engagement Report</title>
  </head>
  <body style="font-family: Inter, Arial, sans-serif; margin: 32px; color: #101828;">
    <div style="border-left: 6px solid ${accent}; padding-left: 12px; margin-bottom: 18px;">
      <h1 style="margin: 0; font-size: 24px;">FM Engagement Report</h1>
      <div style="color: #667085; font-size: 13px;">Generated by PIOS Consulting Workbench</div>
    </div>
    <div style="font-size: 14px; line-height: 1.5;">${escaped}</div>
  </body>
</html>`
}

export async function POST(req: NextRequest, context: { params: Promise<RouteParams> }) {
  try {
    const { id } = await context.params
    const auth = await requireOwnedEngagement(req, id)
    if ('error' in auth) return auth.error

    const { admin, engagement } = auth
    const format = (req.nextUrl.searchParams.get('format') ?? 'html').toLowerCase() as ReportFormat
    if (!['markdown', 'html', 'pdf'].includes(format)) {
      return NextResponse.json({ error: 'format must be markdown|html|pdf' }, { status: 400 })
    }

    const body = (await req.json().catch(() => ({}))) as {
      branding?: { logo_url?: string; color_scheme?: string }
    }

    const [{ data: steps }, { data: frameworks }, { data: risks }, { data: options }] = await Promise.all([
      admin.from('engagement_steps').select('*').eq('engagement_id', id).order('step_number', { ascending: true }),
      admin.from('engagement_frameworks').select('*').eq('engagement_id', id).order('created_at', { ascending: false }),
      admin
        .from('engagement_risks')
        .select('*, risk_library:fm_risk_library(risk_code,title)')
        .eq('engagement_id', id)
        .order('risk_score', { ascending: false }),
      admin.from('fm_options').select('*').eq('engagement_id', id).order('option_number', { ascending: true }),
    ])

    const markdown = toMarkdown({
      engagement,
      steps: steps ?? [],
      frameworks: frameworks ?? [],
      risks: risks ?? [],
      options: options ?? [],
    })

    const html = markdownToHtml(markdown, body.branding?.color_scheme ?? '#6349ff')
    const content = format === 'markdown' ? markdown : html

    const { data: deliverable, error } = await admin
      .from('engagement_deliverables')
      .insert({
        engagement_id: id,
        deliverable_type: format,
        title: `${engagement.title} Report (${format.toUpperCase()})`,
        content,
        metadata: {
          generated_from: 'fm_report_generator',
          format,
          branding: body.branding ?? null,
          note:
            format === 'pdf'
              ? 'PDF format currently stored as print-ready HTML payload for downstream rendering.'
              : null,
        },
      })
      .select('*')
      .single()

    if (error) throw error

    return NextResponse.json({
      report: deliverable,
      report_url: `/platform/consulting/engagements?engagement=${id}&report=${deliverable.id}`,
    })
  } catch (err: unknown) {
    return apiError(err)
  }
}
